apiVersion: v1
kind: Service
metadata:
  name: adminsite
  namespace: ai-demo
spec:
  selector:
    app: adminsite
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
