apiVersion: v1
kind: Service
metadata:
  name: storefront
  namespace: ai-demo
spec:
  selector:
    app: storefront
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
